version: 2
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - test-36
      - test-37
      - deploy:
          requires:
            - test-36
            - test-37
          filters:
            branches:
              only: master

jobs:
  test-36:
    docker:
      - image: circleci/python:3.6.7
    steps:
      - checkout
      - run:
          name: create virtual environment
          command: |
            python -m venv venv
      - run:
          name: install tox
          command: |
            . venv/bin/activate
            pip install --upgrade pip wheel setuptools
            pip install tox
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            tox -e py36-requests216-tenacity50
            tox -e py36-requests216-tenacity51
            tox -e py36-requests217-tenacity50
            tox -e py36-requests217-tenacity51
            tox -e py36-requests218-tenacity50
            tox -e py36-requests218-tenacity51
            tox -e py36-requests219-tenacity50
            tox -e py36-requests219-tenacity51
            tox -e py36-requests220-tenacity50
            tox -e py36-requests220-tenacity51
            tox -e py36-requests221-tenacity50
            tox -e py36-requests221-tenacity51
            tox -e py36-requests222-tenacity50
            tox -e py36-requests222-tenacity51
      - store_artifacts:
          path: test-reports
          destination: test-reports
  test-37:
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: create virtual environment
          command: |
            python -m venv venv
      - run:
          name: install tox
          command: |
            . venv/bin/activate
            pip install --upgrade pip wheel setuptools
            pip install tox
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            tox -e py37-requests216-tenacity50
            tox -e py37-requests216-tenacity51
            tox -e py37-requests217-tenacity50
            tox -e py37-requests217-tenacity51
            tox -e py37-requests218-tenacity50
            tox -e py37-requests218-tenacity51
            tox -e py37-requests219-tenacity50
            tox -e py37-requests219-tenacity51
            tox -e py37-requests220-tenacity50
            tox -e py37-requests220-tenacity51
            tox -e py37-requests221-tenacity50
            tox -e py37-requests221-tenacity51
            tox -e py37-requests222-tenacity50
            tox -e py37-requests222-tenacity51
      - store_artifacts:
          path: test-reports
          destination: test-reports
  deploy:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: install python dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -e .[deploy]
      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = $PYPI_USERNAME" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: create packages
          command: |
            rm -rf dist/*
            python setup.py sdist
      - run:
          name: upload to pypi
          command: |
            . venv/bin/activate
            python upload_new_package.py
